testP2/modeldemo/urls.py
from django.conf.urls import include, url
from . import views
urlpatterns = [
    url(r'^show', views.show,name='show2'),
    url(r'^tes',views.test,name='test3'),
    url(r'^ge',views.get123),
    url(r'index$',views.index,name='index'),
    url(r'login$',views.login,name='login'),
    url(r'loginhanle$',views.login_hanle,name='login_han'),
    url(r'loginout$',views.loginout,name='loginout'),
]

testP2/testP2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from modeldemo import views
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^m/', include('modeldemo.urls',namespace='model1')),
    url(r'^yy77/', views.test,name='qwe')
]

testP2/modeldemo/models.py
from django.db import models

# Create your models here.
class CoManager(models.Manager):
    def get_queryset(self):
        return super(CoManager, self).get_queryset().all()
    def add_Co(self,name,number,major):
        c = College()
        c.cname = name
        c.cnumber = number
        c.cmajor =major
        c.save()
        return c
    def del_Co(self,name):
        c = College.bm2.get(cname=name)
        c.delete()
    def del_Co2(self,name):
        c = College.bm2.get(cname=name)
        c.isDelete = 1
        c.save()
        return c
    def alter(self,name,newname):
        c = College.bm2.get(cname=name)
        c.cname = newname
        c.save()
        return c
class College(models.Model):
    cname = models.CharField(max_length=30)
    cnumber = models.IntegerField()
    cmajor = models.CharField(max_length=30)
    isDelete = models.BooleanField(default=0)


    def __str__(self):
        return '%s'%self.cname
    class Meta():
        db_table = '学院表'
        ordering = ['id']
    bm1 = models.Manager()
    bm2 = CoManager()
class Student(models.Model):
    sname = models.CharField(max_length=30)
    ssex = models.BooleanField(default=1)
    sdate = models.DateTimeField()
    swj = models.ForeignKey('College')
    isDelete = models.BooleanField(default=0)

    def __str__(self):
        return '%s'%self.sname

    class Meta():
        db_table = '学生表'
        ordering = ['-id']

testP2/modeldemo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import *
from django.core.urlresolvers import reverse
from datetime import *
from django.db.models import *

# Create your views here.
def get123(request):
    b=get_object_or_404(College,pk = 999)
    return redirect('/show')
def show(request):
    list1 = College.bm2.all()
    return render(request,'modeldemo/show.html',{'list':list1})

def test(request):
    # stu = Student.objects.filter(swj__cname=)
    return render(request,'modeldemo/test.html',{'li':0})

def index(request):
    pass
def login(request):
    pass
def login_hanle(request):
    pass
def loginout(request):
    pass

testP2/modeldemo/templates/modeldemo/get1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
asd
</body>
</html>

testP2/modeldemo/templates/modeldemo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
你好{{ uname }}
<hr>
<a href="{% url 'model1:login' %}">登录</a>
<hr>
<a href="{% url 'model1:loginout' %}">退出</a>

</body>
</html>

testP2/modeldemo/templates/modeldemo/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="login_hanle.html">
    <input type="text" name="uname"/>
    <input type="submit" value="登录">
</form>
</body>
</html>

testP2/modeldemo/templates/modeldemo/login_hanle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

testP2/modeldemo/templates/modeldemo/loginout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

testP2/modeldemo/templates/modeldemo/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        {% for foo in list %}
{#            {{ foo.pk }}#}
            <li><a href = {% url 'model1:test3' %}>{{ foo.cname }}</a></li>
        {% endfor %}

    </ul>
</body>
</html>

testP2/modeldemo/templates/modeldemo/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
test
</body>
</html>