bolg/app/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    # 首页
    url(r'^index/$',views.index,name='ind'),
    # 列表页
    url(r'^detall/(\d+)/$',views.detall,name='det'),
    # 编写页
    url(r'^edgitpage/$',views.edgitpage,name='edg'),
    #提交
    url(r'^edgitpageHandle/$',views.edgitpageHandle,name='edgHan'),
    #修改
    url(r'^revise/(\d*)$',views.revise,name='revise'),
    #修改2
    url(r'^reviseHandle(\d*)$',views.revisehandle,name='revisehandle'),
    #删除
    url(r'^delete/(\d*)$',views.delete,name='delete'),

]

bolg/bolg/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/',include('app.urls',namespace='blog')),
]

bolg/app/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200,null=False,default='请添加标题')
    content = models.TextField()
    pub_datetime = models.DateTimeField(auto_now=True)
    read = models.IntegerField()
    isDelete = models.BooleanField(default=False)

bolg/app/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.core.urlresolvers import reverse
from .models import *
# Create your views here.
#首页的
def index(request):
    list1 = Article.objects.filter(isDelete=False)

    return render(request,'modo/index.html',{'list':list1})
#列表的
def detall(request,id):
    article = Article.objects.get(pk = id)
    return render(request, 'modo/detall.html',{'art':article})
#编写的
def edgitpage(request):
    return render(request, 'modo/edgitpage.html')
#编辑提交
#编写的
def edgitpageHandle(request):
    title1 = request.POST.get('title')
    content1 = request.POST.get('content')
    a = Article()
    if title1 == '':
        title1 = '请输入标题'
    a.title = title1
    a.content = content1
    a.read = 0
    a.save()
    return redirect(reverse('blog:ind'))
def revise(request,id):
    r = Article.objects.get(pk =id)
    return render(request,'modo/revise.html',{'dx':r})

def revisehandle(request,id):
    t = request.POST.get('title')
    c = request.POST.get('content')
    a = Article.objects.get(pk = id)
    a.title = t
    a.content = c
    a.save()
    return redirect(reverse('blog:ind'))

def delete(request,id):
    o = Article.objects.get(pk=id)
    o.delete()
    return redirect(reverse('blog:ind'))

bolg/app/templates/edggitpageHandle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bolg/app/templates/modo/detall.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static from staticfiles %}
    <style type="text/css">
        body{
            background-image: url({% static 'img/3.jpg' %});
        }
        .div1{
            width: 1335px;
            height: 500px;
        }
        .p1{
            font-size: 20px;
{#            text-align: center;#}
            margin: 50px 100px 0px 100px;
        }
        .xg{
            color: black;
            width: 100px;
            height: 50px;
            text-decoration: none;
            display: block;
            height: 30px;
            text-align: center;
            line-height: 30px;
            background-color: pink;
            opacity: 0.6;
        }
        .a1{
            margin-left: 1000px;
        }
        .a2{
            margin-left: 1000px;
        }

    </style>
</head>
<body>
{#<img src="{% static 'img/2.jpg'%}" alt="">#}
<div class="div1">
    <p class="p1"> 标题: {{ art.title }}</p>
    <a href="{% url 'blog:revise' art.id %}"class="xg a1">修改</a>
    <br>
    <p class="p1">内容: {{ art.content }}</p>
    <p class="p1">修改时间: {{ art.pub_datetime }}</p>
    <a href="{% url 'blog:delete' art.id %}"class="xg a2">删除</a>
</div>
</body>
</html>

bolg/app/templates/modo/edgitpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>写</title>
    {% load static from staticfiles %}
    <style type="text/css">
        body{
            background-image: url("{% static 'img/2.jpg' %}");
        }
        .pp{
            opacity: 0.7;
        }
    </style>
</head>
<body>
<form method="post" action="{% url 'blog:edgHan' %}">
    {% csrf_token %}
    标题<input type="text" name="title" class="pp"><br>
    内容<textarea name="content" id="" cols="30" rows="10"style="height: 300px;width: 800px" class="pp"></textarea>
    <input type="submit" value="提交">

</form>
</body>
</html>

bolg/app/templates/modo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static from staticfiles %}
    <style type="text/css">
        body{
            background-image: url({% static 'img/2.jpg' %});
        }
        ul{
            list-style: none;
        }
        .a1{
            text-decoration: none;
            color: black;
            font-size: 19px;
            font-weight: bold;
        }
        .hh{
            display: block;
            margin-left: 40px;

        }
        .a2{
            text-decoration: none;
            color: black;
        }
    </style>
</head>
<body>
<div>
    <h1 class="hh">这是博客</h1>
    <h4 class="hh"><a href="{% url 'blog:edg' %}" class="a2">编辑博客</a></h4>
    <ul>
        {% for foo in list %}
            <li><a href="{% url 'blog:det' foo.id %}" class="a1">{{ foo.title }}</a></li>
        {% endfor %}

    </ul>
</div>

</body>
</html>

bolg/app/templates/modo/revise.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static from staticfiles %}
    <style type="text/css">
        body{
            background-image: url("{% static 'img/2.jpg' %}");
        }
        .pp{
            opacity: 0.7;
        }
    </style>
</head>
<body>
<form method="post" action="{% url 'blog:revisehandle' dx.id %}">
    {% csrf_token %}
    标题<input type="text" name="title" value='{{ dx.title }}' class="pp p1"><br>
    内容<textarea name="content" id="" cols="30" rows="10"style="height: 300px;width: 800px" class="pp p2">{{ dx.content }}</textarea>
    <input type="submit" value="修改" class="t1">

</form>
</body>
</html>

bolg/app/templates/reviseHandle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>