incloud/in/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
urlpatterns = [

    url(r'^index/', views.index, name='index'),
    url(r'^ok/', views.ok,name='ok'),
    url(r'^denglu/', views.denglu,name='denglu'),
    url(r'^hello/', views.hello,name='hello'),
    url(r'^dd/', views.dd,name='dd'),
]

incloud/incloud/urls.py
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^in/',include('in.urls',namespace='in'))
]

incloud/in/models.py
from django.db import models

# Create your models here.
class Mimi(models.Model):
    user=models.CharField(max_length=20)
    pwd=models.CharField(max_length=20)

incloud/in/views.py
from django.shortcuts import render,redirect
from .models import *
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    return render(request,'in/index.html')
def ok(request):
    user=request.POST.get('user','')
    pwd=request.POST.get('pwd','')
    a=Mimi()
    a.user=user
    a.pwd=pwd
    a.save()
    return redirect(reverse('in:index'))
def denglu(request):
    return render(request,'in/denglu.html')
def dd(request):
    c=request.POST.get('user','')
    b=request.POST.get('pwd','')
    print(c)
    a=Mimi.objects.get(user=c)
    if a.pwd == b:
        return render(request,'in/worry.html')
    else:
        return render(request, 'in/welcome.html')
def hello(request):
    return render(request,'in/hello.html')

incloud/in/templates/in/denglu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{% url 'in:dd' %}">
    <input type="text" name="user" >
    <input type="text" name="pwd">
    <input type="submit" value="提交">
</form>
</body>
</html>

incloud/in/templates/in/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'in:index' %}">注册</a>
<a href="{% url 'in:denglu' %}">登录</a>
</body>
</html>

incloud/in/templates/in/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{% url 'in:ok' %}">
    <input type="text" name="user" >
    <input type="text" name="pwd">
    <input type="submit" value="提交">
</form>
</body>
</html>

incloud/in/templates/in/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
用户不存在
</body>
</html>

incloud/in/templates/in/worry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
欢迎光临
</body>
</html>