jishi/app/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^index$',views.index,name='index'),
    url(r'^register$',views.register,name='register'),
    url(r'^login$',views.login,name='login'),
    url(r'^loginHandle$',views.loginHandle,name='loginHandle'),
    url(r'^registerHandle$',views.registerHandle,name='registerHandle'),
    url(r'^liuyan$',views.liuyan,name='liuyan'),
    url(r'^cun$',views.cun,name='cun'),
    url(r'^xiangq/(\d*)$',views.xiangq,name='xiangq'),
]

jishi/jishi/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^jishi/', include('app.urls',namespace='jishi')),
]

jishi/app/models.py
from django.db import models

# Create your models here.
class Leveo(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=40)
    site = models.CharField(max_length=100)
    message = models.TextField()
    class Meta():
        db_table = 'Leveo'

class User(models.Model):
    zhe = models.CharField(max_length=20,unique=True)
    mm = models.CharField(max_length=50)
    class Meta():
        db_table = 'User1'

jishi/app/views.py
# Create your views here.
def xiangq(request,id):
    p = Leveo.objects.filter(pk = id)
    return render(request,'app/xiangq.html',{'p':p})
def cun(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    address = request.POST.get('address')
    message = request.POST.get('message')
    n = Leveo()
    n.name = name
    n.email = email
    n.site =address
    n.message = message
    n.save()
    return redirect(reverse('jishi:index'))
def index(request):
    p = Leveo.objects.all()
    return render(request,'app/index.html',{'p':p})
def login(request):
    return render(request,'app/login.html')
def register(request):
    return render(request,'app/register.html')
def registerHandle(request):
    zh = request.POST.get('zh')
    mm1 = request.POST.get('mm')
    mm = doPwd(mm1)
    a = User()
    a.zhe = zh
    a.mm = mm
    a.save()
    return redirect(reverse('jishi:index'))

def liuyan(request):
    return render(request,'app/留言板.html')
def loginHandle(request):
    zh = request.POST.get('zh')
    if zh == '':
        return redirect(reverse('jishi:login'))
    mm1 = request.POST.get('mm')
    mm = doPwd(mm1)
    a = User.objects.get(zhe=zh)
    if a.mm == mm or zh =='':
        return redirect(reverse('jishi:index'))
    else:
        return redirect(reverse('jishi:login'))

def doPwd(pwd):
    '''sha1编码'''
    mysha1 = hashlib.sha1()
    mysha1.update(pwd.encode('utf-8'))
    pwd = mysha1.hexdigest()
    return pwd

jishi/app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>这是主页</h2>
<a href="{% url 'jishi:register' %}">去注册</a>
<a href="{% url 'jishi:login' %}">去登录</a>
<a href="{% url 'jishi:liuyan' %}">去留言</a>
<br>
<br>
这里是留言↓ <br>
{% for foo in p %}
    <a href="{% url 'jishi:xiangq' foo.id %}">{{ foo.name }}的留言</a> <br>
{% endfor %}

</body>
</html>

jishi/app/templates/app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'jishi:loginHandle' %}" method="post">
    <h2>这是登录页面</h2>
    账号<br><input type="text" name="zh">
    密码<br><input type="password" name="mm">
    <input type="submit" value="登录">
</form>
</body>
</html>

jishi/app/templates/app/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'jishi:registerHandle' %}" method="post">
    <h2>这是注册页面</h2>
    账号<br><input type="text" name="zh">
    密码<br><input type="password" name="mm">
    <input type="submit" value="注册">

</form>
</body>
</html>

jishi/app/templates/app/xiangq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for foo in p %}
    留言人:<span>{{ foo.name }}</span><br><br>
    留言:<span>{{ foo.message }}</span><br><br>
    <br><br><br><br>
{% endfor %}

</body>
</html>

jishi/app/templates/app/留言板.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/css/style.css">
	<style>
		.smart-green {
			margin-left: auto;
			margin-right: auto;
			max-width: 500px;
			background: #F8F8F8;
			padding: 30px 30px 20px 30px;
			font: 12px Arial, Helvetica, sans-serif;
			color: #666;
			border-radius: 5px;
			-webkit-border-radius: 5px;
			-moz-border-radius: 5px;
		}

		.smart-green h1 {
			font: 24px "Trebuchet MS", Arial, Helvetica, sans-serif;
			padding: 20px 0px 20px 40px;
			display: block;
			margin: -30px -30px 10px -30px;
			color: #FFF;
			background: #9DC45F;
			text-shadow: 1px 1px 1px #949494;
			border-radius: 5px 5px 0px 0px;
			-webkit-border-radius: 5px 5px 0px 0px;
			-moz-border-radius: 5px 5px 0px 0px;
			border-bottom: 1px solid #89AF4C;
		}

		.smart-green h1 > span {
			display: block;
			font-size: 11px;
			color: #FFF;
		}

		.smart-green label {
			display: block;
			margin: 0px 0px 5px;
		}

		.smart-green label > span {
			float: left;
			margin-top: 10px;
			color: #5E5E5E;
		}

		.smart-green input[type="text"], .smart-green input[type="email"], .smart-green textarea, .smart-green select {
			color: #555;
			height: 30px;
			line-height: 15px;
			width: 100%;
			padding: 0px 0px 0px 10px;
			margin-top: 2px;
			border: 1px solid #E5E5E5;
			background: #FBFBFB;
			outline: 0;
			-webkit-box-shadow: inset 1px 1px 2px rgba(238, 238, 238, 0.2);
			box-shadow: inset 1px 1px 2px rgba(238, 238, 238, 0.2);
			font: normal 14px/14px Arial, Helvetica, sans-serif;
		}

		.smart-green textarea {
			height: 100px;
			padding-top: 10px;
		}


		.smart-green .button {
			background-color: #9DC45F;
			border-radius: 5px;
			-webkit-border-radius: 5px;
			-moz-border-border-radius: 5px;
			border: none;
			padding: 10px 25px 10px 25px;
			color: #FFF;
			text-shadow: 1px 1px 1px #949494;
		}

		.smart-green .button:hover {
			background-color: #80A24A;
		}

		.error-msg{
			color: red;
			margin-top: 10px;
		}
		.success-msg{
			color: #80A24A;
			margin-top: 10px;
			margin-bottom: 10px;
		}
	</style>
</head>
<body>
<a href="{% url 'jishi:index' %}">返回主页</a>
<form action="{% url 'jishi:cun' %}" method="post" class="smart-green">
    {% csrf_token %}
    <h1>留言信息
        <span>请留下你的信息.</span>
    </h1>
    <label>
        <span>姓名 :</span>
        <input id="name" type="text" name="name" class="error" placeholder="请输入您的姓名"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>邮箱 :</span>
        <input id="email" type="email" value="" name="email" placeholder="请输入邮箱地址"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>联系地址 :</span>
        <input id="address" type="text" value="" name="address" placeholder="请输入联系地址"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>留言 :</span>
        <textarea id="message" name="message"  placeholder="请输入你的建议"></textarea>
        <div class="error-msg"></div>
    </label>
    <div class="success-msg"></div>
    <label>
        <span>&nbsp;</span>
        <input type="submit" class="button" value="提交"/>
    </label>
    <input type='hidden' name='csrfmiddlewaretoken' value='SfHkbL4feo1G00sJQtbO7TtLN4c2BUwa' />
</form>

</body>
</html>